// src/constants/userConstants.js
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPLOAD_USER_PROFILE_IMAGE = 'UPLOAD_USER_PROFILE_IMAGE';
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';
export const UPDATE_USER_CONTACT = 'UPDATE_USER_CONTACT';
export const UPDATE_USER_QUALIFICATION = 'UPDATE_USER_QUALIFICATION';
export const UPDATE_OTHER_QUALIFICATION = 'UPDATE_OTHER_QUALIFICATION';
export const UPDATE_USER_JOB_ROLE = 'UPDATE_USER_JOB_ROLE';
export const USER_UPDATE_SKILLS = 'USER_UPDATE_SKILLS';
export const USER_UPDATE_EXPERIENCE = 'USER_UPDATE_EXPERIENCE';
// userConstants.js
export const USER_UPDATE_PREFERRED_JOB_LOCATION = 'USER_UPDATE_PREFERRED_JOB_LOCATION';
// actionTypes.js
export const USER_UPLOAD_RESUME = 'USER_UPLOAD_RESUME';



